# Generated by Django 3.1.5 on 2021-01-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contacts'},
        ),
    ]
