# Generated by Django 3.1.5 on 2021-01-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_apis', '0002_auto_20210107_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
    ]
